version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
     
    steps:
      - checkout       
      - run: |
             sudo apt-get update 
             curl -sSL https://get.rvm.io | bash -s stable
             sudo apt-get install ruby2.7
             rvm --default use 2.7
             ruby -v
      - run: |
             sudo apt-get update
             sudo apt-get install rubocop   

      - run: |  
             gem install bundler
             gem update bundler   
      - run: |  
             bundle update ruby-progressbar
      - run: |
             bundle
      - run: |
             sudo apt-get install libboost-all-dev
      - run: |
             rails test
      - run: |
             rubocop .